"""
R&S FSL/FSW .dfl file parser for WaveSight EMC.

The .dfl format is an OLE Compound Document (Microsoft Structured Storage)
generated by Rohde & Schwarz spectrum analyzers controlled via EMC32.

Structure identified from Save_005.fsl.dfl:
- SaveRecallManager/FSLSpectrumAnalyzer/.../Current Settings  -> sweep params (start/stop Hz as float64)
- SaveRecallManager/FSLSpectrumAnalyzer/.../All Traces        -> multiple trace arrays (float32)
- SaveRecallManager/REC/.../Current Settings                  -> recorder settings (start freq)
- SaveRecallManager/REC/.../Peak-Final List                   -> peak list (template, often blank)
- SaveRecallManager/FSLGeneralSetup/.../All Limit Lines       -> CISPR limit line definitions

Trace extraction strategy:
  Scan every byte offset in the All Traces stream for the n_points-length float32 block
  where ALL values are in [-140, 0] dBm (excludes positive artifacts from metadata) and
  the score = max_value + 0.5 * dynamic_range is highest. This reliably selects the
  Peak Hold Max detector trace (the most relevant for EMC pass/fail assessment) over
  background noise-sweep traces and binary metadata arrays.
"""

from __future__ import annotations

import io
import struct
from typing import Any, Dict, List, Optional, Tuple

try:
    import olefile
    _OLEFILE_AVAILABLE = True
except ImportError:
    _OLEFILE_AVAILABLE = False


class DFLParseError(ValueError):
    pass


def _is_olefile_available() -> bool:
    return _OLEFILE_AVAILABLE


def _read_start_stop_hz(ole: "olefile.OleFileIO") -> Tuple[float, float]:
    """Extract start and stop frequencies (Hz) from settings streams."""
    start_hz = 100e6
    stop_hz = 3000e6

    for stream_path in ole.listdir():
        name = stream_path[-1]
        full = "/".join(stream_path)
        if "Current Settings" not in name:
            continue
        try:
            data = ole.openstream(stream_path).read()
        except Exception:
            continue

        # REC/Current Settings stores the sweep start at ~offset 321 as a double (Hz)
        if "REC" in full:
            for i in range(0, min(len(data) - 8, 600)):
                try:
                    v = struct.unpack_from("<d", data, i)[0]
                    if abs(v - 100e6) < 1000:
                        start_hz = v
                    if 2990e6 <= v <= 3010e6:
                        stop_hz = v
                except Exception:
                    pass

        # FSLSpectrum settings may have broader range info
        if "FSLSpectrum" in full:
            for i in range(0, len(data) - 8):
                try:
                    v = struct.unpack_from("<d", data, i)[0]
                    if 1e4 <= v <= 1e10:
                        if v < start_hz and v >= 9e3:
                            start_hz = v
                        if v > stop_hz and v <= 8e9:
                            stop_hz = v
                except Exception:
                    pass

    return start_hz, stop_hz


def _infer_n_points(raw: bytes) -> int:
    """
    Infer the number of sweep points from the stream.

    The R&S FSL default is 501 sweep points for a full-span measurement.
    We check common values to see which produces the candidate block with
    the highest dynamic range (most signal variation = real measurement).
    """
    candidates = [501, 499, 601, 401, 301, 801, 1001]
    best_n = 501
    best_dyn: float = 0.0

    for n in candidates:
        if len(raw) < n * 4:
            continue
        limit = len(raw) - n * 4
        for offset in range(0, min(limit + 1, 5000), 4):
            try:
                block = [struct.unpack_from("<f", raw, offset + i * 4)[0] for i in range(n)]
            except Exception:
                continue
            # Require all values strictly below -5 dBm to exclude metadata near-zero arrays
            if not all(-140.0 <= v < -5.0 for v in block):
                continue
            dyn = max(block) - min(block)
            if dyn > best_dyn:
                best_dyn = dyn
                best_n = n

    return best_n


def _find_best_trace(raw: bytes, n_points: int) -> Optional[List[float]]:
    """
    Scan the raw stream byte-by-byte to find the float32 block of `n_points` values
    that best represents the actual EMC measurement:
      - All values < -5 dBm (excludes near-zero marker/metadata arrays)
      - All values >= -140 dBm (valid dBm range)
      - Highest dynamic range (most signal variation = Peak Hold Max trace)

    Real EMC measurements with ref = -20 dBm and att = 0 dB never exceed ~-5 dBm.
    Near-zero metadata blocks (marker amplitudes, scaling data) all have max very close
    to 0 dBm, so the < -5 dBm requirement cleanly separates them.

    Returns the best matching amplitude list, or None.
    """
    best: Optional[List[float]] = None
    best_score: float = -1e9
    n = len(raw)
    limit = n - n_points * 4

    for offset in range(0, limit + 1):
        try:
            block = [struct.unpack_from("<f", raw, offset + i * 4)[0] for i in range(n_points)]
        except Exception:
            continue

        # All values must be real EMC amplitudes: in range and strictly below -5 dBm
        if not all(-140.0 <= v < -5.0 for v in block):
            continue

        # Score by dynamic range: the Peak Hold Max trace has the largest spread
        # because it captures strong emission peaks against the noise floor.
        dynamic_range = max(block) - min(block)
        score = dynamic_range

        if score > best_score:
            best_score = score
            best = block

    return best


def _extract_traces(ole: "olefile.OleFileIO", start_hz: float, stop_hz: float) -> Dict[str, List[float]]:
    """
    Extract the best trace from each All Traces stream found in the .dfl file.

    For FSLSpectrumAnalyzer traces, n_points is inferred by scanning the stream.
    The selected block is the float32 sequence that most closely represents measured
    EMC emission data (all values ≤ 0 dBm, highest dynamic range + peak).
    """
    traces: Dict[str, List[float]] = {}

    for stream_path in ole.listdir():
        name = stream_path[-1]
        full = "/".join(stream_path)
        if "All Traces" not in name:
            continue

        try:
            raw = ole.openstream(stream_path).read()
        except Exception:
            continue

        # Infer sweep-point count from stream content
        n_points = _infer_n_points(raw)

        best = _find_best_trace(raw, n_points)
        if best is None:
            # Fallback: search over a ±15% range of point counts
            for alt_n in range(int(n_points * 0.85), int(n_points * 1.15) + 1):
                if alt_n == n_points:
                    continue
                best = _find_best_trace(raw, alt_n)
                if best is not None:
                    break

        if best:
            if "FSLSpectrum" in full:
                traces["peak_max"] = best
            elif "REC" in full:
                # Only use REC trace if no FSLSpectrum trace found
                if "peak_max" not in traces:
                    traces["rec_trace"] = best

    return traces


def parse_dfl(file_bytes: bytes) -> Dict[str, Any]:
    """
    Parse a Rohde & Schwarz .dfl (EMC32 save set) file.

    Returns a dict with:
      - frequencies_mhz: list of frequency values (MHz)
      - amplitudes_dbm: list of amplitude values (dBm)
      - start_mhz / stop_mhz: sweep limits
      - points: number of sweep points
      - active_trace: name of the selected trace
      - source_format: "dfl"

    Raises DFLParseError if the file cannot be parsed.
    """
    if not _OLEFILE_AVAILABLE:
        raise DFLParseError(
            "A biblioteca 'olefile' não está instalada. Execute: pip install olefile"
        )

    try:
        ole = olefile.OleFileIO(io.BytesIO(file_bytes))
    except Exception as exc:
        raise DFLParseError(f"Não foi possível abrir o arquivo .dfl: {exc}") from exc

    try:
        start_hz, stop_hz = _read_start_stop_hz(ole)
        all_traces = _extract_traces(ole, start_hz, stop_hz)
    finally:
        ole.close()

    if not all_traces:
        raise DFLParseError(
            "Nenhum dado de trace encontrado no arquivo .dfl. "
            "Verifique se o arquivo foi gerado por um analisador R&S FSL/FSW via EMC32."
        )

    # Priority: peak_max (most relevant for EMC) > rec_trace > first available
    priority = ["peak_max", "rec_trace"]
    selected_key = next((k for k in priority if k in all_traces), next(iter(all_traces)))
    amplitudes = all_traces[selected_key]
    n = len(amplitudes)

    if n < 2:
        raise DFLParseError("Dados insuficientes no arquivo .dfl (menos de 2 pontos).")

    freq_step = (stop_hz - start_hz) / (n - 1)
    frequencies = [start_hz + freq_step * i for i in range(n)]

    # Convert Hz to MHz for WaveSight compatibility
    freq_mhz = [f / 1e6 for f in frequencies]

    # Convert dBm to dBµV (50 ohm system: dBµV = dBm + 107)
    amplitudes_dbuv = [a + 107.0 for a in amplitudes]

    return {
        "frequencies_mhz": freq_mhz,
        "amplitudes_dbuv": amplitudes_dbuv,
        "start_mhz": start_hz / 1e6,
        "stop_mhz": stop_hz / 1e6,
        "points": n,
        "active_trace": selected_key,
        "all_traces": {k: v for k, v in all_traces.items()},
        "source_format": "dfl",
    }


def dfl_to_csv_bytes(file_bytes: bytes) -> bytes:
    """
    Convert a .dfl file to CSV bytes compatible with the WaveSight /upload endpoint.
    Returns UTF-8 encoded CSV with columns: frequency_mhz, amplitude_dbuv.
    """
    result = parse_dfl(file_bytes)
    freq_mhz = result["frequencies_mhz"]
    amps = result["amplitudes_dbuv"]

    lines = ["frequency_mhz,amplitude_dbuv"]
    for f, a in zip(freq_mhz, amps):
        lines.append(f"{f:.4f},{a:.4f}")

    return "\n".join(lines).encode("utf-8")
